service: in-your-free-time

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["DynamoDBTable", "Arn"] }
  environment:
    TABLE_NAME: ${self:custom.tableName}

custom:
  defaultStage: stg
  tableName: "in-your-free-time-${self:provider.stage}"
  environment:
    stg: ${file(./sls_env/stg.yml)}
    prd: ${file(./sls_env/prd.yml)}

functions:
  app:
    handler: index.handler
    environment: ${self:custom.environment.${self:provider.stage}}
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

resources:
  Resources:
    DynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
