service: in-your-free-time

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'