name: s3-deploy

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed] #他のjobがある想定でこの設定にしている

jobs:
  UploadStaticFiles:
    name: Upload static files
    if: github.event.pull_request.merged == true #マージされたときのみこのjobを実行する
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install --prefix frontend/
      - run: npm run prd-build --prefix frontend/ --if-present
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        working-directory: frontend/dist
        run: aws s3 sync . s3://freetime.sakudev.net --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --exclude "README.md"
